### ISSUE TITLE
Error When I Try Run On Replit

### ISSUE THREAD

**Issue by ShohanOS** [Joshwgaming/Discord.js-Bad-Links#3]
![Screenshot_2022-02-09-13-11-03-43](https://user-images.githubusercontent.com/95225090/153139975-96015bf4-5cce-4ada-906f-eea720ee70d6.png)
How To Fix This Error? Please Tell me on Discord 
https://discord.gg/amayoritown

**Comment by jwilliams0n** [comment]
Sorry for late response, will look into this over the next few days.

**Comment by ShohanOS** [comment]
> Sorry for late response, will look into this over the next few days.

Np Waiting For a fix

**Comment by ShohanOS** [comment]
> Sorry for late response, will look into this over the next few days.

@Joshwgaming Hey i found Solution from another bot src same error, This Error Cuz Node version is incompatible
I needed to update node version

**Comment by jwilliams0n** [comment]
Glad to hear you fixed it. Let me know if you come across any more issues!
